In [1]:
import numpy as np

# Array İşlemleri
* \* operatörü iki liste arasında tanımsızdır, hata verir.

In [2]:
a = [1 ,2 ,3]
b = [2, 4, 6]

a * b

TypeError: can't multiply sequence by non-int of type 'list'

* list ile integer çarpılırsa integer kadar concenetion yapar

In [3]:
[2, 8, 6] * 3

[2, 8, 6, 2, 8, 6, 2, 8, 6]

* list ile list toplandığında concention yapar

In [4]:
[2, 8, 6] + [2, 8, 6] + [2, 8, 6]

[2, 8, 6, 2, 8, 6, 2, 8, 6]

* \* operatörü iki numpy array'i arasında tanımlıdır. element-wise (eleman bazlı) çarpma yapar.

In [5]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x * y

array([ 2,  8, 24])

* element-wise çarpımı yapıldığı için iki array'in boyutu aynı olmalıdır.

In [6]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8, 10])

x * y

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

* iki numpy array'i toplandığında element bazlı toplama işlemi yapılır.

In [8]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x + y

array([ 3,  6, 11])

* bir numpy array'i integer değer ile çarpılırsa element bazlı çarpma işlemi gerçekleşir.

In [9]:
x = np.array([1, 2, 3])

x * 2

array([2, 4, 6])