In [11]:
import numpy as np

In [5]:
x = np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
y = np.zeros((2 ,2, 4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# Array Attributes

### Shape

In [8]:
x.shape

(2, 3)

In [9]:
y.shape

(2, 3, 4)

### ndim

In [12]:
x.ndim

2

In [13]:
y.ndim

3

### size

In [14]:
x.size

6

In [15]:
y.size

16

### dtype

In [16]:
x.dtype

dtype('float64')

In [17]:
y = np.full((3, 2), "5.2")

y.dtype

dtype('<U3')