In [1]:
import numpy as np

# Reshaping
* Yeniden boyutlandırılacak array, reshap yapıldıktan sonra da aynı eleman sayısına sahip olmalıdır, yoksa hata alınır.

In [3]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.ndim

1

In [5]:
a.size

10

In [6]:
a.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
a.reshape(2,5).ndim

2

* Eleman sayısı tutmazsa hata alınır.

In [10]:
a.reshape(2, 6)

ValueError: cannot reshape array of size 10 into shape (2,6)

### -1 ile Boyuta Karar Verme

In [11]:
a.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
a.reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Yeni Boyut Ekleme

In [13]:
a[np.newaxis, : ]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [14]:
a[np.newaxis, : ].shape

(1, 10)

In [15]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [17]:
a[:, np.newaxis].shape

(10, 1)

* veya **None** yazarak yeni boyut eklenebilir.

In [19]:
a[None, : ]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [22]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])