In [1]:
import numpy as np

# Concatenation

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* np.concatenation ile numpy array'leri ve python listleri birleştirilebilir.

In [5]:
l = [10, 11]
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [7]:
l = [10, 11, 11.2]
np.concatenate([a, b, l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [8]:
l = [10, 11, "11.2"]
np.concatenate([a, b, l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U11')

* python tuple'ları da listeler gibi numpy array'leri ile birleştirilebilir.

In [9]:
l = (10, 11)
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

### Size Mismatch

* birleştirilecek array'ların birleştirilecek kenaralarının boyutları eşit olmalı.

In [22]:
a

array([1, 2, 3, 4])

In [23]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

In [24]:
a.shape

(4,)

In [25]:
x.shape

(2, 3)

In [26]:
np.concatenate([a, x])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [27]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([x, x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])