In [1]:
import numpy as np

# Splitting

In [2]:
l = np.arange(10, 90, 10)
l

array([10, 20, 30, 40, 50, 60, 70, 80])

In [3]:
np.split(l, [2, 6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [4]:
np.split(l, [3, 5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

### Split'in Sonucunu Biren Çok Değişkene Eşitleme

In [5]:
a, b = (1, 10)

In [6]:
a

1

In [7]:
b

10

In [8]:
x, y, z = np.split(l, (2, 6))

In [9]:
x

array([10, 20])

In [10]:
y

array([30, 40, 50, 60])

In [11]:
z

array([70, 80])

### Vsplit

In [27]:
a = np.arange(20).reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [29]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3]])

In [30]:
np.vsplit(a, [1])[1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
np.vsplit(a, [2, 3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

### Hsplit

In [15]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [18]:
np.hsplit(a, [2])[0]

array([[ 0,  1],
       [10, 11]])

In [19]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
np.hsplit(a, [2])[0].shape

(2, 2)

In [23]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [26]:
np.hsplit(a, [2, 4])[0]

array([[ 0,  1],
       [10, 11]])

In [25]:
np.hsplit(a, [2, 4])[1]

array([[ 2,  3],
       [12, 13]])

In [24]:
np.hsplit(a, [2, 4])[2]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19]])