In [1]:
import numpy as np

# sorting

In [2]:
a = np.random.randint(99, size=10)
a

array([86, 20, 10, 86, 89, 91, 45, 33, 16, 56])

In [3]:
np.sort(a)

array([10, 16, 20, 33, 45, 56, 86, 86, 89, 91])

In [4]:
a

array([86, 20, 10, 86, 89, 91, 45, 33, 16, 56])

In [5]:
a.sort()

In [6]:
a

array([10, 16, 20, 33, 45, 56, 86, 86, 89, 91])

### argsort
verilen array'ı elemanlarının sıralanmış halindeki index'lerini döndürür.

In [7]:
a = np.random.randint(99, size=10)
a

array([53, 77,  0, 23, 89, 29,  4, 64, 84, 55])

In [9]:
idxs = np.argsort(a)
idxs

array([2, 6, 3, 5, 0, 9, 7, 1, 8, 4], dtype=int64)