In [15]:
import numpy as np

# Multidimensional Array'lerin Elemanlarına Ulaşma

In [16]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
a[0]

array([1, 2, 3, 4, 5])

In [18]:
a[1]

array([ 6,  7,  8,  9, 10])

In [19]:
a[0, 0]

1

In [20]:
a[0][0]

1

In [21]:
a.ndim

2

In [22]:
a[0].ndim

1

### Eleman Değiştirme

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[1 ,1] = 10
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

* eklenen yeni veri, array'in veri tipi ne ise ona cast olur; array'ın veri tipini değiştirmez

In [25]:
a[1 ,1] = 20.40
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a[1, 1] = "30"
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
a[1, 1] = "30.4"
a

ValueError: invalid literal for int() with base 10: '30.4'

### Slice Indexing

In [28]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

* başını veya sonunu blirtmezsen, belirtmediğin kısmın tamamını alır

In [30]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

* ikili atlayarak alır

In [36]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [37]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

* belirli bir row'u ve tüm cloumn'ları yada belirli bir column'u ve tüm rowları almak 

In [39]:
a[:, 3] # 3. column ve tüm row'lar

array([ 4,  9, 14, 19])

In [41]:
a[::2, 3] # 3. column ve 2'li atlayarak row'lar

array([ 4, 14])

In [43]:
a[0, :] # 1. row, tüm column'lar

array([1, 2, 3, 4, 5])

In [45]:
a[0, 2:5] # 2-5 arasında kalan column'ların 0. row'unu al

array([3, 4, 5])

In [48]:
a[:2, :3] # 2. row'a kadar ve 3. column'a kadar olanları al

array([[1, 2, 3],
       [6, 7, 8]])

In [56]:
a[0:2, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [51]:
a[::, :4]  # tüm array'in 4. column'a kadar olan kısmını al

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [55]:
a[:, :4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [54]:
a[:2, ::] # tüm array'ın 2. row'una kadar olan kısmını al

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])