In [1]:
import numpy as np

# Fancy Indexing
* Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları veya belirli sayıda atlayarak eleman almayı gördük. Fancy indexing ile birkaç belirli indexteki elemanları alabileceğiz.

In [8]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
idxs = [4, 5, 7, 10]

In [12]:
a[idxs]

array([ 5,  6,  8, 11])

* index array'ının içinde indexler hangi sıraya sahipse çıktı da o sırada olur.

In [13]:
idxs = [4, 5, 7, 1]
a[idxs]

array([5, 6, 8, 2])

In [20]:
a = a.reshape(3, 4)

In [22]:
a[0, [1, 3]]

array([2, 4])

In [23]:
a[0:, [1, 3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [30]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
idx1 = [1, 3, 2]
idx2 = [3, 0, 2]
a[idx1, idx2]

array([ 8, 15, 12])

In [34]:
a[idx1, idx2].shape

(3,)

In [35]:
a[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

### Fancy Index'in değerini belirli bir sonuca eşitlemek

In [40]:
a = np.arange(1, 15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
a[[1, 2, 3]] = 20
a

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
a[[1, 2, 3]] = 100, 200, 300
a

array([  1, 100, 200, 300,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])