In [9]:
import numpy as np

# Subarray

Sub array'lar bir array'ın bir veya daha çok elemanını gösteren array'lardir. Bir subarray değiştirildiğinde bbu değişiklik asıl array'de de gerçekleşir. Aynı durum tam tersi için de geçerlidir.

In [10]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
b = a[:2, :3]
b

array([[1, 2, 3],
       [6, 7, 8]])

In [12]:
b.ndim

2

In [13]:
b[0, 0] = 100

In [14]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [15]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## Copy

Bir array'ın bir kısmını veya tamamını başka bir değişken array olarak kaydetmek istiyorsak copy() fonksiyonu kullanılır.

In [16]:
b = a[:2, :3].copy()
b[0, 1] = 200
b

array([[100, 200,   3],
       [  6,   7,   8]])

In [17]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])