# Array Veri Tipini Manuel Belirleme

In [2]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4.6])
x

array([1. , 2. , 3. , 4.6])

In [4]:
x = np.array([1, 2, 3, 4.6], dtype="int32")
x

array([1, 2, 3, 4])

In [5]:
x = np.array([1, 2, 3, 4.6], dtype="str")
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [8]:
# Dönüşüm yapılamayan durumlar vardır.
x = np.array(["a"], dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [9]:
x = np.array(["5"], dtype="int32")
x

array([5])

In [3]:
x=np.array(["4.2"],dtype="int32")
x

ValueError: invalid literal for int() with base 10: '4.2'