In [1]:
import numpy as np

# Conditional Indexing
array içinde filtreleme yapmayı sağlar

In [11]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [13]:
a[a<5]

array([1, 2, 3, 4])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
filt = a < 3

In [16]:
a[filt]

array([1, 2])

In [22]:
b = np.random.randint(10, size = 10)
b

array([0, 2, 8, 6, 1, 7, 5, 9, 9, 8])

In [23]:
a == b

array([False,  True, False, False, False, False, False, False,  True,
       False])

In [24]:
a[a==b]

array([2, 9])

In [25]:
b[a==b]

array([2, 9])

In [26]:
a == [1]

array([ True, False, False, False, False, False, False, False, False,
       False])

* and ve or numpy'da kullanılmaz

In [28]:
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
a[(a < 3) | (a > 5)]

array([ 1,  2,  6,  7,  8,  9, 10])

In [35]:
filt =(a > 3) & (a <= 5)

In [36]:
a[filt]

array([4, 5])

### Filtrenin Değili

Bir array'in değilin ! veya not ile değil ~ ile alırız

In [38]:
filt = a < 5
filt

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [42]:
a[!filt]

SyntaxError: invalid syntax (4141566624.py, line 1)

In [43]:
a[not filt]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
a[~filt]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
filt

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [46]:
~filt

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

### Multidimentional Array'lerde Conditional Indexing

In [48]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
type(a)

numpy.ndarray

In [50]:
type(a < 7)

numpy.ndarray

In [51]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [52]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [53]:
a[a<7].shape

(6,)

In [55]:
a = [1, 2, 3, None]
a == None

False

In [56]:
a = np.array([1, 2, 3, None], dtype=object)
a == None

array([False, False, False,  True])

In [57]:
a[a==None]

array([None], dtype=object)