In [1]:
import numpy as np

# Sum
* Toplama fonksiyonu

In [3]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

* bir array'deki tüm değerleri toplama

In [4]:
np.sum(a)

210

### belirli bir koşulu sağlayan elemanları toplama
* filteleme yaptığımızda boolean değerlerden oluşan filtreyi toplarsak, true değerler 1 değerine sahip, false değerler 0 değerine sahip olduğundan 0'lar ve1'lerin toplamı sonuç olarak döner

In [6]:
filt = a<5
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
np.sum(filt)

4

* filtrelediğimiz değerlerin gerçek değerine ulaşmak için:

In [9]:
a[filt]

array([1, 2, 3, 4])

In [8]:
np.sum(a[filt])

10

In [10]:
filt = (a>5) & (a<9)
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [11]:
np.sum(filt)

3

In [12]:
a[filt]

array([6, 7, 8])

In [13]:
np.sum(a[filt])

21

In [14]:
np.sum(a[~filt])

189

### Belirli axis üzerinde toplama yapma

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
np.sum(a, axis=0)

array([34, 38, 42, 46, 50])

In [17]:
np.sum(a, axis=1)

array([15, 40, 65, 90])