In [1]:
import numpy as np

# All
* Tüm elemanlar verilern şartları sağlıyorsa true döndürür

In [19]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [21]:
np.all(a>-1)

True

In [22]:
filt = a>-1

In [23]:
np.all(filt, axis=0)

array([ True,  True,  True,  True,  True])

In [24]:
np.all(filt, axis=1)

array([ True,  True,  True,  True])

In [25]:
filt = a>5
filt

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [26]:
np.all(filt, axis=0)

array([False, False, False, False, False])

In [27]:
np.all(filt, axis=1)

array([False, False,  True,  True])

In [28]:
a=np.arange(1,21).reshape(4,5)

np.all(a>8,axis=1)

array([False, False,  True,  True])

# Any
* Herhangi bir eleman verilen şartları sağlıyorsa true döndürür

In [29]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [30]:
np.any(a>17)

True

In [31]:
np.any(a>17, axis=0)

array([False, False,  True,  True,  True])

In [32]:
np.any(a>17, axis=1)

array([False, False, False,  True])