In [1]:
import numpy as np

# Tüm Elemanları 0 Olan Array Oluşturma 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype = 'str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Tüm Elemanları 0 Olan Multidimensional Array Oluşturma

3 satır ve 4 sütundan oluşan bir array oluşturma

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros(3, 4)

TypeError: Cannot interpret '4' as a data type

In [6]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros([2, 4, 8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [9]:
np.zeros(2, dtype= 'int')

array([0, 0])

In [10]:
np.zeros((1, 2), dtype='str')

array([['', '']], dtype='<U1')

In [11]:
np.zeros((2, 3), dtype='bool')

array([[False, False, False],
       [False, False, False]])