In [1]:
import numpy as np

# Belirtilen Bir Elemandan Oluşan Array Oluşturmak

In [2]:
np.full((4, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [4]:
np.full(4, 5, 5)

TypeError: Cannot interpret '5' as a data type

In [5]:
np.full(4, 5)

array([5, 5, 5, 5])

In [7]:
np.full((2, 3), "a")

array([['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [8]:
np.full((3, 2), 5.2)

array([[5.2, 5.2],
       [5.2, 5.2],
       [5.2, 5.2]])

In [9]:
str(5.2)

'5.2'

In [10]:
np.full((2, 4), 5.2, dtype='str')

array([['5', '5', '5', '5'],
       ['5', '5', '5', '5']], dtype='<U1')

In [11]:
np.full((3, 2), "5.2")

array([['5.2', '5.2'],
       ['5.2', '5.2'],
       ['5.2', '5.2']], dtype='<U3')