In [1]:
import numpy as np

# Ardışık Sayılardan Array Oluşturma

In [2]:
np.arange(0, 12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
np.arange(2, 12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [5]:
np.arange(2, 12, -2)

array([], dtype=int32)

In [6]:
np.arange(12, 2, -2)

array([12, 10,  8,  6,  4])

In [7]:
np.arange(13, 1, -3)

array([13, 10,  7,  4])