In [1]:
import numpy as np

# Normal Dağılım Değerlerinden Oluşan Array Oluşturma

* np.random.normal(mean, std, array_size)

In [3]:
np.random.normal(0, 1, (4, 5))

array([[ 0.21805999,  2.22678894,  0.9654618 , -1.62330981, -0.35007281],
       [-0.53573594, -2.09219706,  1.48549119,  0.17152623, -0.0095972 ],
       [-0.62945869,  0.73713878,  0.77914055,  0.43361431,  0.13571044],
       [-0.13877567, -1.00593461,  0.91106879,  1.11689337,  2.00434684]])

In [12]:
np.random.normal(0, 100, (4, 3))

array([[  33.23792135,   75.31860598, -123.75125702],
       [ -20.67621622,   39.59673083,  -55.04228965],
       [  86.80473973, -152.07945598, -109.78786937],
       [ -18.52605006,   15.73145383,  -25.64024387]])

In [11]:
np.random.normal(10, 100, (4, 3))

array([[-131.82962412,  -95.39693222, -160.30237372],
       [ 122.26122531, -132.06779278,  143.50855723],
       [ 138.34772041,   99.97618141,   73.38962737],
       [  93.67532367,   57.38105911,   60.97095959]])

In [14]:
np.random.normal(10, 1, (4, 3))

array([[12.02899694, 10.48191019, 10.39109595],
       [10.47327787,  8.63304055,  9.49932329],
       [10.91370964, 10.14358854,  8.84872057],
       [10.19922155,  9.78812943,  9.46811795]])