In [2]:
import numpy as np

# Identity (Birim) Matrix Oluşturma

* np.eye(low, high)
* [low, high)

In [3]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [4]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [8]:
np.eye(2, dtype='int')

array([[1, 0],
       [0, 1]])